In [1]:
#Question 1 : Write a Python program to convert an array to an ordinary list with the same items.
#We can use the np.tolist() function.

import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)
print(type(my_array),"\n")

my_list = my_array.tolist()
print(my_list)
print(type(my_list))



[1 2 3 4 5]
<class 'numpy.ndarray'> 

[1, 2, 3, 4, 5]
<class 'list'>


In [2]:
#Question 2: Write a NumPy program to compute the sum of the diagonal elements of a given array.
#Hint: There are two possible methods to solve this problem: 1.Manually (without direct function). 2.Using the trace function

import numpy as np
#Manually method:
my_array = np.random.randint(0,10 ,size=(5,5))
print(my_array)
sum = my_array[0,0]+my_array[1,1]+my_array[2,2]+my_array[3,3]+my_array[4,4]
print("La somme des éléments diagonaux est:",sum,"\n")

#Using the trace function method:
my_array = np.random.randint(0,10 ,size=(5,5))
print(my_array)
sum = my_array.trace()
print("La somme des éléments diagonaux est:",sum,"\n")

#Or
my_array = np.random.randint(0,10 ,size=(5,5))
print(my_array)
sum = np.trace(my_array)
print("La somme des éléments diagonaux est:",sum)

[[9 9 4 7 0]
 [3 3 0 5 7]
 [2 8 0 8 8]
 [8 5 6 7 4]
 [1 4 9 7 3]]
La somme des éléments diagonaux est: 22 

[[9 7 9 6 4]
 [2 5 1 8 3]
 [4 0 3 5 3]
 [7 3 3 3 5]
 [7 2 7 3 1]]
La somme des éléments diagonaux est: 21 

[[8 0 1 3 5]
 [2 9 5 3 4]
 [9 4 5 6 7]
 [9 6 1 0 4]
 [6 3 4 9 0]]
La somme des éléments diagonaux est: 22


In [3]:
#Question 3 : Given an array of your choice, get all the values higher than X:
#If a = [[1,2],[3,5]] and x = 2 : then 3 and 5 are higher than 2.

x=15
my_array = np.random.randint(0,25 ,size=(3,2))
print(my_array,"\n")

#Nous créons un masque booléen a > x qui renvoie un tableau booléen de la même forme que a avec des valeurs 
#True là où la condition est satisfaite et des valeurs False sinon. Ensuite, nous utilisons ce tableau booléen 
#pour indexer le tableau original a et récupérer toutes les valeurs qui satisfont la condition.
higher_than_x= my_array[my_array > x] 
print("Toutes les valeurs supérieures à", x, "dans le tableau sont :", higher_than_x)

[[20 14]
 [ 7  9]
 [18  7]] 

Toutes les valeurs supérieures à 15 dans le tableau sont : [20 18]


In [4]:
#Or

# Définir la valeur de x
x = 15
# Créer un tableau avec des valeurs aléatoires
my_array = np.random.randint(0, 25, size=(3, 2))

# Afficher le tableau
print("Tableau :")
print(my_array)

# Initialiser une liste pour stocker les valeurs supérieures à x
values_above_x = []

# Parcourir toutes les valeurs du tableau en les aplatissant avec flatten()
for i in my_array.flatten():
    if i > x:
        # Si la valeur est supérieure à x, l'ajouter à la liste
        values_above_x.append(i)

# Afficher les valeurs supérieures à x
if len(values_above_x) > 0:
    print("\nLes valeurs supérieures à", x, "dans le tableau sont :")
    for value in values_above_x:
        print(value)
else:
    print("\nAucune valeur n'est supérieure à", x, "dans le tableau.")

Tableau :
[[14  9]
 [16  0]
 [19 14]]

Les valeurs supérieures à 15 dans le tableau sont :
16
19


In [5]:
#Question 4: Given two arrays, A & B have the same shape. The task is to apply addition by hand: C is the new array. 

import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = np.add(A,B)
print(C,"\n")

#OR
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = np.array([[0,0,0],[0,0,0]])

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        C[i, j] = A[i, j] + B[i, j]
print(C,"\n")        

#OR

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = np.zeros_like(A) # Créer un tableau C de même forme que A, initialisé à zéro

for i in range(A.shape[0]):  # Boucler sur les lignes de A et B
    for j in range(A.shape[1]):  # Boucler sur les colonnes de A et B
        C[i, j] = A[i, j] + B[i, j] # Ajouter chaque élément de A à l'élément correspondant de B
print(C,"\n") 

#OR
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])

rows, cols = A.shape   # Obtenir le nombre de lignes et de colonnes de A

C = np.empty_like(A)   # Créer un tableau vide de même forme que A pour stocker le résultat

# Parcourir chaque élément de A et B et ajouter les éléments correspondants pour obtenir C
for i in range(rows):
    for j in range(cols):
        C[i,j] = A[i,j] + B[i,j]

print("A =\n", A)
print("B =\n", B)
print("C =\n", C)


[[ 8 10 12]
 [14 16 18]] 

[[ 8 10 12]
 [14 16 18]] 

[[ 8 10 12]
 [14 16 18]] 

A =
 [[1 2 3]
 [4 5 6]]
B =
 [[ 7  8  9]
 [10 11 12]]
C =
 [[ 8 10 12]
 [14 16 18]]


In [6]:
#Question 5 : Write a NumPy program to subtract the mean of each row of a given matrix. Hint: use the mean function.

# Définir la matrice
C = np.array([[21,452,43],[4,5,6],[7,8,9]])
# Calculer la moyenne de chaque ligne
D = np.mean(C,axis=1)
# Soustraire les moyennes de chaque ligne de la matrice
C_normalized = C - D.reshape(-1, 1)


print("Matrice originale :\n", C)
print("Moyenne de chaque ligne de la matrice:\n",D)
print("Matrice normalisée par soustraction de la moyenne de chaque ligne:\n", C_normalized)

Matrice originale :
 [[ 21 452  43]
 [  4   5   6]
 [  7   8   9]]
Moyenne de chaque ligne de la matrice:
 [172.   5.   8.]
Matrice normalisée par soustraction de la moyenne de chaque ligne:
 [[-151.  280. -129.]
 [  -1.    0.    1.]
 [  -1.    0.    1.]]


In [7]:
#OR
import numpy as np

# Matrice d'exemple 3x4
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print("La matrice:\n",A)
# Calcul des moyennes de chaque ligne
row_means = np.mean(A, axis=1)
print("Moyennes de chaque ligne :\n", row_means)

# Réorganisation des moyennes de chaque ligne en un vecteur colonne 2D
row_means_col = row_means.reshape(-1, 1)
print("Vecteur colonne des moyennes de chaque ligne : \n", row_means_col)
print("Shape : ", row_means_col.shape)

# Soustraction de chaque élément de chaque ligne de la matrice A par la moyenne de cette ligne
A_normalized = A - row_means_col
print("Matrice A normalisée par soustraction de la moyenne de chaque ligne : \n", A_normalized)



La matrice:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Moyennes de chaque ligne :
 [ 2.5  6.5 10.5]
Vecteur colonne des moyennes de chaque ligne : 
 [[ 2.5]
 [ 6.5]
 [10.5]]
Shape :  (3, 1)
Matrice A normalisée par soustraction de la moyenne de chaque ligne : 
 [[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]
